accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    AccountListView,
    AccountCreateView,
    CategoriesListView,
    CategoriesCreateView,
    ReceiptListView,
    ReceiptCreateView,
)


urlpatterns = [
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "acounts/create/", AccountCreateView.as_view(), name="account_create"
    ),
    path("categories/", CategoriesListView.as_view(), name="expense_list"),
    path(
        "categories/create/",
        CategoriesCreateView.as_view(),
        name="expense_create",
    ),
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(username, None, password)
            if user is not None:
                login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
        context = {"form": form}
        return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from receipts.models import Account, ExpenseCategory, Receipt


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")


class CategoriesListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class CategoriesCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("expense_list")


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

receipts/templates/accounts/create.html
{% extends 'base.html' %} {% block content %}
<div class="form_design">
  <h1>Create Account</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="button_design">Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %} {% block content %}
<h1>Accounts</h1>
<table>
  <thead>
    <tr>
      <th>Account Name</th>
      <th>Number</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for account in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{ account.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styling.css' %}" />
    <title>Expense Tracker</title>
  </head>
  <body>
    <nav>
      <ul class="navigation">
        {% if user.is_authenticated %}
        <li class="nav_item"><a href="{% url 'home' %}">Receipts</a></li>
        <li class="nav_item">
          <a href="{% url 'account_list' %}">Accounts</a>
        </li>
        <li class="nav_item">
          <a href="{% url 'expense_list' %}">Expense Categories</a>
        </li>
        <li class="nav_item">
          <a href="{% url 'receipt_create' %}">Add Receipt</a>
        </li>
        <li class="nav_item">
          <a href="{% url 'account_create' %}">Add Account</a>
        </li>
        <li class="nav_item">
          <a href="{% url 'expense_create' %}">Add Expense</a>
        </li>
        <li class="nav_item"><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li class="nav_item"><a href="{% url 'login' %}">Login</a></li>
        <li class="nav_item"><a href="{% url 'signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/categories/create.html
{% extends 'base.html' %} {% block content %}
<div class="form_design">
  <h1>Create Expense Category</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="button_design">Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %} {% block content %}
<h1>Expense Categories</h1>
<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Number of Receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list %}
    <tr>
      <td>{{ category.name }}</td>
      <td>{{ category.receipts.all|length }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %} {% block content %}
<div class="form_design">
  <h1>Create Receipt</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="button_design">Create</button>
  </form>
</div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}
<h1>Receipts</h1>
<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipt_list %}
    <tr>
      <td>{{ receipt.vendor }}</td>
      <td>${{ receipt.total }}</td>
      <td>${{ receipt.tax }}</td>
      <td>{{ receipt.date|date:"m-d-Y" }}</td>
      <td>{{ receipt.category.name }}</td>
      {% if receipt.account.name is not None %}
      <td>{{ receipt.account.name }}</td>
      {% else %}
      <td>Cash</td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}